In [1]:
import torch
vec=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(vec)
print(vec.shape)
print(vec.size())
print(vec[:-1])

tensor([0., 1., 2., 3., 4., 5., 6.])
torch.Size([7])
torch.Size([7])
tensor([0., 1., 2., 3., 4., 5.])


In [16]:
mat=torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])
print(mat)
print(mat.size())
print(mat.dim())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])
2


In [19]:
#broadcasting
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
print(m1+m2)
m3=torch.FloatTensor([[3],[4]])
print(m1+m3)

tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [24]:
t=torch.FloatTensor([[1,2],
                     [3,4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [32]:
#view
v=torch.FloatTensor([[[0,1,2],
                     [3,4,5]],
                    [[6,7,8],
                    [9,10,11]]])
print(v)
print(v.size())
print(v.view(-1,3))
print(v.view(-1,3).size())
print(v.view(-1,1,3))
print(v.view(-1,1,3).size())

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [37]:
#squeeze
s=torch.FloatTensor([[0],[1],[2]])
print(s)
print(s.size())
print(s.squeeze())
print(s.squeeze().size())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [44]:
#unsqueeze
u=torch.FloatTensor([0,1,2])
print(u.shape)
print(u.unsqueeze(0))
print(u.unsqueeze(0).shape)
print(u.unsqueeze(1))
print(u.unsqueeze(1).shape)
ut=u.float()
print(ut)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])


In [47]:
#concatenate
x=torch.FloatTensor([[1,2],
                     [3,4]])
y=torch.FloatTensor([[5,6],
                     [7,8]])
c1=torch.cat([x,y],dim=0)
c2=torch.cat([x,y],dim=1)
print(c1)
print(c2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [6]:
a=torch.FloatTensor([1,2])
b=torch.FloatTensor([3,4])
c=torch.FloatTensor([5,6])
print(torch.stack([a,b,c]))
print(torch.stack([a,b,c],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [10]:
x=torch.FloatTensor([[1,2],
                     [3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
